drift-labs/protocol-v2

programs/clearing_house/src/math/amm.rs
current impl leads to bid/ask being out of whack (validate.rs) when an lp adds shares and adjusts k + base reserves
soln: update bid/ask reserves too in update k
=> update bid/ask reserves in update k 

sdk/src/factory/bigNum.ts
BigNum detects the locale of the current browser now and uses its delimiters. Also had to fix two other functions that were breaking when it was a non-US locale that used commas for the spacers.
=> sdk: fix bignum locale issues

sdk/src/factory/bigNum.ts
BigNum.toNotional was showing "000" when the value was "0" in locales that don't use a standard dot as the delimiter. This should fix. Also made the conditions for appending 0s less complex because I think there was some unnecessary complexity there.
=> sdk: fix toNotional method for 0-values in euro locales

CHANGELOG.md, programs/drift/src/controller/amm.rs, programs/drift/src/controller/amm/tests.rs, programs/drift/src/controller/pnl.rs, programs/drift/src/math/orders.rs, programs/drift/src/math/spot_balance.rs
- when spot utilization is high we dont want to settle negative pnl which would lead to more borrows 
- also added a new helper fcn `calculate_spot_market_utilization`
=> high-util-neg-pnl-settles

CHANGELOG.md, programs/drift/src/controller/orders.rs, programs/drift/src/controller/orders/amm_jit_tests.rs, programs/drift/src/controller/orders/tests.rs
1) for risk decreasing trades, dont use maintenance buffer ratio when calculating leverage
2) dont check maker maintenance ratio if they weren't filled
=> program: more leniency in allowing risk decreasing trades for perps

CHANGELOG.md, sdk/src/tx/retryTxSender.ts
Addresses this:
https://drift-protocol.slack.com/archives/C01V3SKCS95/p1671474413750489
/
https://twitter.com/bfriel_/status/1604641581855698944?s=21&t=hwlZd6lJB4p9ZG3WjpQCXw
=> sdk: expect signTransaction from wallet adapters to return a copy

CHANGELOG.md, sdk/src/events/fetchLogs.ts
Seeing this error from some mainnet RPCs (rpcpool), this fix should address it:
=> sdk: fix deprecated calls to `@solana/web3.js`

sdk/src/driftClient.ts
When creating a polling subscriber the `DriftClient` constructor uses values provided by `DriftClientConfig` param first and otherwise falls back to value returned by `getMarketsAndOraclesForSubscription(config.env)`. When creating a websocket subscriber however the constructor only uses the value provided by the config. It lead to some confusion on my part when trying to create a new `DriftClient` instance using a config that only specified the `env` property but not the `oracleInfos` etc. of the config object. It seems like this should be consistent unless there is some reason I am missing.
=> fix: use consistent oracles and market indexes when creating account subscriber in DriftClient constructor

sdk/src/examples/makeTradeExample.ts, sdk/src/math/trade.ts
I noticed the oracle data is required in the functions called by `calculateTradeSlippage`, so I added this to the example and made the argument required in the `trade.ts` function.
=> fix(sdk): oracle info required for calculating trade slippage

CHANGELOG.md, sdk/src/driftClient.ts
Also allow changing order type and trigger price
=> sdk: change modify order params to be object

sdk/examples/phoenix.ts, sdk/package.json, sdk/src/index.ts, sdk/src/phoenix/phoenixFulfillmentConfigMap.ts, sdk/src/phoenix/phoenixSubscriber.ts
=> Add phoenix subscriber

sdk/src/types.ts
it's saved this way in the db, think it makes more sense too
=> sdk: change enum

sdk/src/driftClient.ts, sdk/src/user.ts
PR adds options to request the slot of the account data when requesting specific userAccount data (perp positions, open orders , ...) how recent the data is currently ambiguous.
User subscribes to recent events. if the event slot is greater than slot of local UserAccount, then local UserAccount data should be considered stale.
if you're concerned about your current base asset amount:
```
// receiving OrderActionRecords via EventSubscriber
// to calculate current base position
const perpPosition = user.getPerpPositionAndSlot(mktIndex);
let currentBase = perpPosition.baseAssetAmount;
if (event.slot > perpPosition.slot) {
currentBase = currentBase.add(event.makerOrderBaseAssetAmount); // use taker or maker value as appropriate
}
```
=> ts-sdk: add slot data to UserAccount getters

sdk/src/driftClient.ts
Using `SystemProgram.createAccountWithSeed` instead of `SystemProgram.createAccount` eliminates the need in an ephemeral signer for the the wrapping SOL transaction. 
This makes the transaction compatible with Smart Wallets that use delayed transaction execution mechanism, e.g. Fuse Wallet
For more in-depth explanation see section "Ephemeral Signers" here: https://fusedocs.framer.website/docs/fuse-intergration-for-app-devs
=> sdk: use createWithSeed when wrapping SOL

sdk/src/dlob/DLOB.ts
The semantics implemented on PR #644 are the inverse of what's documented for the function, and of the usual behavior for filter.
=> BUGFIX: DLOBFilterFcn should indicate if a node is used, not skipped

sdk/src/driftClient.ts, sdk/src/math/trade.ts
SDK part for:
https://linear.app/driftprotocol/issue/DPE-1207/close-related-orders
=> sdk: cancel existing orders tx feature

programs/drift/src/math/amm.rs, programs/drift/src/math/cp_curve.rs, programs/drift/src/math/orders.rs, programs/drift/src/math/orders/tests.rs, programs/drift/src/math/position.rs, programs/drift/src/math/repeg.rs
also deleted an unused bool flag
=> program: add test for max order size with imf

sdk/src/tx/priorityFeeCalculator.ts
Minor fox on priorityFeeCalculator.generateComputeBudgetWithPriorityFeeIx() comment.
=> priorityFeeTriggered is a property, not a method

sdk/src/jupiter/jupiterClient.ts, sdk/src/math/auction.ts
Currently errors are suppressed, but some of these errors from jupiter are helpful for sdk users.
```
{
statusCode: 429,
error: 'Too Many Requests',
message: 'You have exceeded the rate limit of 210 requests per minute.'
}
```
```
{
error: 'AMM was not found, amm_key: 5BUwFW4nRbftYTDMbgxykoFWqWHPzahFSNAaaaJtVKsq'
}
```
=> surface errors from jupiter api

sdk/src/accounts/bulkAccountLoader.ts, sdk/src/accounts/pollingInsuranceFundStakeAccountSubscriber.ts
2 issues fixed in this PR
1. Obvious one that does fix the UI issue is that `fetchIfUnloaded()` is missing in the `subscribe()` function of `pollingInsuranceFundStakeAccountSubscriber`
2. Technically, even if `fetchIfUnloaded()` was missing from `subscribe()`, we expected the `BulkAccountLoader` to still poll and update the data of account.
- However, due to race conditions, particularly transitioning from account unsubscribing to subscribing, the callbackId attached to the account was `undefined` when it was the account's turn to be handled with fresh data on subscribe. Hence even though the correct data was fetched, the callback to attach the data to the account did not execute because it was missing. The callback was only added after the fetch (race conditions at play), but …
=> fix(sdk): add fetchIfUnloaded to pollingIfStakeAccountSubscriber, account loader logic

sdk/src/phoenix/phoenixSubscriber.ts
The SDK currently panics if there's an order in the book where 2^53 < quantity * price < 2^64. This change resolves this problem
=> Fix overflow

CHANGELOG.md, sdk/src/driftClient.ts, sdk/src/tx/utils.ts
optionally return a signed settlePnl tx after closing position so ui can cleanup after closes
=> sdk: add option to get signed settlepnl tix from a market order

sdk/src/userMap/userMap.ts
Allow user to provide an `accountSubscription` when adding a pubkey to `UserMap`, similar to if they were to initialize a new `User`
=> ts-sdk: UserMap api improvement for adding new use

sdk/src/jupiter/jupiterClient.ts
Jupiter API returns this error with `maxAccounts`:
```
{"error":"maxAccounts with swapMode ExactOut is not supported"}
```
=> ts-sdk: remove maxAccounts in jupiter quote if swapMode is ExactOut

sdk/src/tx/fastSingleTxSender.ts
FastSingleTx sender was sending the transaction twice for some unclear reason, both to the main connection and through the additional connections. I've removed the duplicated behavior.
=> BUGFIX: Removing unnecessary duplicate send from FastSingleTxSender

sdk/src/dlob/orderBookLevels.ts, sdk/tests/dlob/test.ts
Fixes an uncrossing bug reported by user. Added test to confirm. You can see the situation in the following screenshots:
1: User's bid is in the second level - 190.588
2: Crossing ask comes in at 190.5, user's bid disappears (and TWO 190.499 levels get created)
I added a test with levels exactly matching the screenshot below. Without the changes to the uncrossL2 method that I added, you will see that it fails.
=> Added handling for uncrossing bug reported by user

sdk/src/priorityFee/driftPriorityFeeMethod.ts, sdk/src/priorityFee/priorityFeeSubscriber.ts, sdk/src/priorityFee/types.ts, tests/deleteInitializedSpotMarket.ts, tests/fillSpot.ts
Usage example:
```
const main = async () => {
const subscriber = new PriorityFeeSubscriber({
frequencyMs: 1000,
priorityFeeMethod: PriorityFeeMethod.DRIFT,
driftPriorityFeeEndpoint: <CACHED_PRIORITY_FEE_ENDPOINT>,
customStrategy: {
calculate: (samples: HeliusPriorityFeeResponse) => {
return samples.result.priorityFeeLevels![
HeliusPriorityLevel.HIGH
];
},
}
});
await subscriber.subscribe();
subscriber.updateMarketTypeAndIndex(MarketType.PERP, 0);
setInterval(() => {
console.log(`Custom strategy: ${JSON.stringify(subscriber.getCustomStrategyResult())}`);
}, 5000);
}
main().catch((err) => {
console.error(err);
});
```
=> add drift priority fee support to PriorityFeeSubscriber

CHANGELOG.md, programs/drift/src/controller/position.rs, programs/drift/src/controller/position/tests.rs, programs/drift/src/state/perp_market.rs
- solves incorrect cost basis for determining settle_pnl when market has high lp turnover + prolonged unsettled
- doesnt impact lp mathematics, just accounting maths for determining safe settle_pnl
- includes cargo test
=> program: fix-track-unsettled-quote-for-lp

sdk/src/dlob/DLOB.ts, sdk/src/math/orders.ts
Allow user to override the buffer in `isOrderExpired` to account for blockchain clock drift
=> ts-sdk: allow override isOrderExpired buffer

sdk/src/user.ts, tests/delistMarketLiq.ts
getMaintenanceMarginRequirement should automatically use liq buffer if user can be liquidated
=> sdk: liquidation buffer improvement

sdk/src/index.ts, sdk/src/tx/baseTxSender.ts, sdk/src/tx/types.ts
* gives `TxSender` a default `TxHandler`
* bring back `getVersionedTransaction` on `TxSender` to maintain backwards compatibility
=> sdk: make TxSender backwards compatible

sdk/src/tx/baseTxSender.ts, sdk/src/tx/txHandler.ts, sdk/src/tx/types.ts, sdk/src/util/computeUnits.ts
`buildTransaction` has some assumptions on priority fee ixs, this uses `generateVersionedTransaction` instead in `TxSender`. Downstream clients will need to make sure update blockhash+height passed instead of just blockhash
Make `buildTransaction` safer by being aware of existing instructions, and properly handling undefined `TxParams`
=> sdk: TxSender use generateVersionedTransaction for get tx

sdk/src/dlob/DLOB.ts
There were several functions that called to getBestNode yet weren't taking a filter function as a parameter.
=> Extending use of DLOBFilterFcn

sdk/src/tx/whileValidTxSender.ts
I do realize there's a @ts-ignore when it gets assigned later, but I am getting an error when attempting to use 2.84.0-beta.2 with bun 1.1.13, which seems to be more strict.
```
error: script "prod" exited with code 1
$ bun run src/index.ts --config-file uncross.config.yaml
45 |             latestBlockhash = tx.SIGNATURE_BLOCK_AND_EXPIRY;
^
error: This assignment will throw because "latestBlockhash" is a constant
at keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/whileValidTxSender.js:45:13
35 |         const latestBlockhash = await this.txHandler.getLatestBlockhashForTransaction();
^
note: The symbol "latestBlockhash" was declared a constant here:
at keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/whileValidTxSender.js:35:15
```
=> latestBlockchash on whileValidTxSender.prepareTx should be mutable

sdk/src/blockhashSubscriber/BlockhashSubscriber.ts
Using a fixed index as the offset is fiddly, given that it requires you to update all calls if the updateIntervalMs were to change.
This version still defaults to the same behavior as the original function.
=> BlockhashSubscriber can take an offset in seconds

.devcontainer/Dockerfile
The dev container is broken. I think this is from a later version of Rust, as it seems to work once we change from Ubuntu to Rust 1.75. I didn't test that it works on this repo, but I tested that it works [here](https://github.com/metaDAOproject/futarchy/blob/develop/.devcontainer/Dockerfile).
=> Fix `Dockerfile` for dev container

sdk/src/dlob/DLOB.ts, sdk/src/orderSubscriber/OrderSubscriber.ts
- DLOB's getBestNode generation is now protected, so that subclasses can access it.
- OrderSubscriber can be subclassed to create a different subclass of DLOB object.
=> Minor changes for DLOB / OrderSubscriber subclassing

CHANGELOG.md, programs/drift/src/controller/token.rs, programs/drift/src/instructions/admin.rs, programs/drift/src/instructions/pyth_pull_oracle.rs, programs/drift/src/instructions/user.rs, programs/drift/src/state/fulfillment_params/serum.rs
`to_account_info().clone()` is an anti-pattern because [`to_account_info`](https://github.com/coral-xyz/anchor/blob/84fdf31d58f4683e810967cffa941013af1dec94/lang/src/lib.rs#L169) already returns an owned `AccountInfo`.
Remove the redundant `clone()` call from `to_account_info().clone()`s.
=> program: remove redundant clones

CHANGELOG.md, programs/drift/src/instructions/keeper.rs
Ensures quote market account is writeable in `spot_market_map`
=> program: fix spot market map in force_cancel_orders

sdk/src/math/spotBalance.ts
This allows us to generate the borrow/lend rates for the full axis of 0-100% utilization for the borrow/lend sidebar graph
=> Add optional currentUtilization param for apr calculation functions

sdk/src/orderSubscriber/OrderSubscriber.ts
This can be problematic if account updates are received out of order, or `tryUpdateUserAccount` is invoked out of order. If an account update for a slot `t-1` is received for an order filled at slot `t`, then the `OrderSubscriber` will erroneously report the open order.
=> Remove delete user in `OrderSubscriber` on filled.

sdk/src/orderSubscriber/OrderSubscriber.ts
This pr is similar to pr #1245. Issue is that it can cause incorrect slot updates. 
For example, a fetch operation results in a user with now no open orders. Subsequently, a slot update arrives prior to this fetch, which orderSubscriber then utilizes due to the user's deletion during the fetch process.
=> Remove delete user in fetch

.github/workflows/main.yml
Reverts drift-labs/protocol-v2#1276
=> Revert "chore: remove drift-competitions from downstream dependency"

programs/drift/src/math/spot_balance.rs
The absence of import was causing a compilation issue when compiling with `drift-rs` feature on
=> add `PERCENTAGE_PRECISION` import for fixing compilation issue

sdk/src/tx/baseTxSender.ts, sdk/src/tx/whileValidTxSender.ts
Allows user to specify whether the underlying tx sender should throw if sendTransaction results in a tx error. Currently it does for types like the while-valid sender (new default is yes). Setting `throwOnTransactionError ` in the constructor allows user to disable this behavior
=> sdk: add option to throw on tx send errors

sdk/src/tx/baseTxSender.ts, sdk/src/tx/types.ts
Breaking change to `BaseTxSender.getVersionedTransaction`. `blockhash` was marked optional but is required by the internal `txHandler.generateVersionedTransaction`, so if a user passes an undefined blockhash, it will throw within `txHandler.generateVersionedTransaction`. Blockhash must be provided now.
=> sdk: enforce blockhash in getVersionedTransaction

sdk/src/driftClient.ts
subAccountId param in getPlaceAndTakePerpOrderIx is not passed all the way down so it throws at getUser when you don't have a subAccountId = 0 because getUser is always evaluating subAccountId to zero with this logic: subAccountId = subAccountId ?? this.activeSubAccountId;
activeSubAccountId seems to always be zero which might be its own problem and maybe where you should start?
Reproduce:
- Initialize a new user (your first user, sub acc id = 0)
- Delete the user
- Initialize a new user (sub acc id = 1)
- client.getPlaceAndTakePerpOrderIx(pass the non zero sub acc id param)
- it tries to use your sub acc id = 0 and throws
```
Error: DriftClient has no user for user id [object Object]_6ZRD5HpC6vic6btP7yjii68ix9HZNoJr4tB9DJ4bBBGs
at DriftClient.getUser …
```
=> getPlaceAndTakePerpOrderIx Fix for passing a subAccountId

sdk/src/driftClient.ts
This commit doesn't fix the problem because my user accs length is > 1 in my case: https://github.com/drift-labs/protocol-v2/commit/29044b61220b3fe0f1c5c4c9bdef39e8bac61b2b
Also, found another place where code breaks bc sub acc id isn't passed (getDepositInstruction).
=> Pass Sub Acc Ids

programs/drift/src/macros.rs, programs/drift/src/math/oracle.rs
motivation: removes noisy oracle validity logs for drift-rs use
saw that there's a `log_validity` bool but can't really control it from the public API
closes #1342
=> Add a crate local msg! macro that can compile out

CHANGELOG.md, sdk/src/driftClient.ts
Fixes a bug where the `subAccountId` of an incoming `UserAccount` doesn't exist on the authority loaded into the `DriftClient` (caused an error with `getPlacesignedMsgTakerOrderIxs`)
=> sdk: account for authority when useMarketLastSlotCache

sdk/src/driftClient.ts, sdk/src/jupiter/jupiterClient.ts
- update `JupiterClient` default API
Read More: https://dev.jup.ag/docs#whats-new
=> refactor(sdk): update jupiter's api url

sdk/src/driftClient.ts
On the Foundation page, there’s a fuel claim. 
It’s necessary to send the claim and stake on a single transaction, it’s required to separate the IXS from the original method.
I tested both on the app and Foundation page and they worked on both.
=> Separate getAddInsuranceFundStakeIxs

sdk/src/accounts/grpcAccountSubscriber.ts, sdk/src/accounts/grpcProgramAccountSubscriber.ts, sdk/src/driftClient.ts
for the [yellowstone-grpc node client](https://github.com/rpcpool/yellowstone-grpc), the [proper way to close a stream](https://github.com/rpcpool/yellowstone-grpc/issues/506#issuecomment-2572991442) is to call `stream.cancel()` and `stream.destroy()`, otherwise the client holds previous connections open, which bogs down the server and eventually _someone_ will force terminate the connection in an unpleasant way.
=> sdk: fix grpc reconnect logic

sdk/src/driftClient.ts, sdk/src/tx/baseTxSender.ts, sdk/src/tx/txHandler.ts
Enable gas sponsorship without API changes by:
- Setting the transaction payer to `wallet.payer?.publicKey ?? wallet.publicKey` at message construction
- Always signing with the user (authority) and then the sponsor (payer) when present
Backward compatible for users without `wallet.payer`.
- Drift SDK always builds transactions with payer = `wallet.publicKey` (user). When trying to sponsor and sign with a different key, signing fails:
- web3.js enforces that only required signers in the message can sign. If the sponsor key isn’t in the message’s required signer set, `VersionedTransaction.sign` throws:
```text
Cannot sign with non signer key
```
- Additionally, there is a branch that, when `wallet.payer` is present, signs only with the payer and can omit the user signature. Many Drift …
=> [ FIX ] `posaune0423/fix tx fee payer`

sdk/src/driftClient.ts, sdk/src/tx/baseTxSender.ts, sdk/src/tx/txHandler.ts
Reverts drift-labs/protocol-v2#1837
caused this error in RetryTxSender:
```
TypeError: tx.partialSign is not a function
at Wallet3.signTransaction (/lib/index.js:275679:12)
at TxHandler.signVersionedTx (/lib/index.js:324492:39)
at RetryTxSender2.sendVersionedTransaction (/lib/index.js:325642:43)
at DriftClient20.sendTransaction (/lib/index.js:337010:32)
at /lib/index.js:1080354:30
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 78)
at async PythCrankerBot.runCrankLoop (/lib/index.js:1080278:5)
at async Timeout._onTimeout (/lib/index.js:1080189:7)
```
=> Revert "[ FIX ] `posaune0423/fix tx fee payer`"
