sdk/src/clearingHouse.ts

Add optional param to initializeUserAccountAndDepositCollateral to specify source account, use wallet as source if param not specified

sdk: deposit from existing subaccount + fix cross collat deposits

---

programs/clearing_house/src/controller/orders.rs
programs/clearing_house/src/controller/orders/amm_jit_tests.rs
programs/clearing_house/src/math/amm.rs
programs/clearing_house/src/math/helpers.rs

fixes for issues discovered in drift-sim

bigz/ kitchen-sink-fixes

---

sdk/tests/amm/test.ts

This file was using spaces instead of tabs and it kept making eslint fail when making commits in the monorepo

sdk: fix tabs for eslint in one file

---

sdk/package.json
sdk/src/driftClient.ts
sdk/yarn.lock

Ummm, so the way github shows the Diff looks really weird, but yeah all this actually changed was moving the order of the functions so the two new methods are together as you scroll down the file, and then adding 3 auction parameters which are needed if you switched the order type to market from something else.

sdk: add more options to modifyOrder

---

sdk/src/events/eventSubscriber.ts
sdk/src/events/fetchLogs.ts
sdk/src/events/types.ts

Added txSigIndex

---

sdk/src/driftClient.ts

If an account has too many open positions / spot markets, user will not be able to deposit. this PR fixes that by using version 0 transactions + address look up tables.

ts-sdk: use LUT for deposit tx

---

CHANGELOG.md
programs/drift/src/controller/orders.rs

Fixes the situation where a maker is a non-0 subaccount of the taker's referrer.

exhaustively search for referrer account

---

sdk/src/factory/bigNum.ts
sdk/tests/bn/test.ts

added switching for financial and scientific notification in BigNum.toMillified

toMillified improvement

---

sdk/src/dlob/orderBookLevels.ts

refactor(sdk): fix assign dlob source size

---

sdk/src/priorityFee/priorityFeeSubscriber.ts

I THINK this might be the cause of the issue in this thread:
https://drift-protocol.slack.com/archives/C02EVD5T98Q/p1705964508479339
Not 100% but I think it's worth a shot, because I definitely got a whoops page on localhost after sitting idle for a while because of this method:

sdk: catch error in priorityFeeSubscriber.load

---

sdk/src/driftClient.ts

Replaced sendRawTransaction with sendTransaction

Market order tx sending improvement

---

sdk/src/dlob/orderBookLevels.ts
sdk/src/driftClient.ts
sdk/src/phoenix/phoenixFulfillmentConfigMap.ts
sdk/src/serum/serumFulfillmentConfigMap.ts
sdk/src/tx/baseTxSender.ts
sdk/tests/dlob/test.ts

This decreases the time to add and subscribe to users by 1 - 2 seconds

refactor(sdk): optimise addAndSubscribeToUsers

---

sdk/src/dlob/orderBookLevels.ts

fix(sdk): grouping l2 levels

---

CHANGELOG.md
programs/drift/src/controller/orders.rs

theres also `last_oracle_valid` that gets updated after `update_amm` but its not utilized in fill

program: is-amm-available-action-validity

---

sdk/src/driftClient.ts

Fixed issues with staking and unstaking from IF when DriftClient has no user attached

DriftClient IF (un)staking bug fixes

---

sdk/src/driftClient.ts
sdk/src/tx/txHandler.ts
sdk/src/tx/utils.ts

Moved isVersionedTransaction to util file to help with consistency

refactored isVersionedTransaction method

---

CHANGELOG.md
sdk/src/accounts/webSocketDriftClientAccountSubscriber.ts
sdk/src/addresses/pda.ts
sdk/src/config.ts

try to address https://github.com/drift-labs/protocol-v2/issues/1214

sdk: avoid spamming getAccountInfo in drift client ws sub

---

sdk/src/config.ts
sdk/src/driftClient.ts
sdk/src/tokenFaucet.ts
sdk/src/tx/baseTxSender.ts
sdk/src/tx/fastSingleTxSender.ts
sdk/src/tx/forwardOnlyTxSender.ts
sdk/src/tx/retryTxSender.ts
sdk/src/tx/txHandler.ts
sdk/src/tx/whileValidTxSender.ts

Updated commitment defaults from "processed" (Because anchor provider's default values are "processed") to "confirmed"
Based on information gathered here : https://x.com/jordaaash/status/1774892864847368230

Update commitment config

---

README.md
sdk/README.md

Minor change to readme to try improve salience for available Drift documentation

README improvement

---

programs/drift/src/state/order_params.rs

- order sanitize for oracle limits
- [TODO] initialize market information

program: add and fix msg logs

---

sdk/src/driftClient.ts
sdk/src/idl/drift.json
sdk/src/swift/swiftOrderSubscriber.ts
sdk/src/swift/types.ts
sdk/tests/dlob/test.ts
tests/placeAndMakeSwiftPerp.ts
tests/placeAndMakeSwiftPerpBankrun.ts

follow up from #1416 to improve the api for both taker and maker

Use a signed swift order params type

---

.github/workflows/main.yml

want to start automated updates to rust sdk stuff on program updates

Send program update notifications to drift-rs repos [no ci]

---

CHANGELOG.md
sdk/src/math/spotBalance.ts
sdk/src/user.ts

Needed to call these for amplify for a user that doesn't exist yet. Maintained backwards compatibility

sdk: move functions out to spotBalance

---

sdk/src/driftClient.ts
tests/placeAndMakeSignedMsgBankrun.ts

follow up to #1608 needed to dehex this

fix: dehexify in getPlaceSignedMsgTakerPerpOrderIxs

---

sdk/src/slot/SlotSubscriber.ts

Emits `newSlot` event on `connection.getSlot()`

refactor(sdk): emit newSlot event on initial subscribe call
